### ISSUE TITLE
Make look nice in 1.8.3, currently looks bad man

### ISSUE THREAD

**Issue by JohnMcLear** [JohnMcLear/ep_table_of_contents#39]
@seballot <3

**Comment by Oremountainflorian** [comment]
Haha I'd really appreciate seeing that fixed :) 

I longingly waited for the update with V1.8.3 since https://github.com/JohnMcLear/ep_table_of_contents/issues/32 to fix the overlapping problem with chat/chat + user always on screen option but now it overlaps the toolbar

**Comment by seballot** [comment]
Hi ! can you be more specific and provide screenshot please? for me it works nicely...

**Comment by JohnMcLear** [comment]
Afaik I pulled and published and it should be fixed now.  Please update and confirm Oreo

**Comment by techware01** [comment]
Hi, 
i added the updated version to our etherpad. Now the ToC is displayed on the left side instead of on the right like it was before. The position looks correct. 
But now there is a problem with the text color:
We applied a dark theme with the skinvariants builder. Now the text color of the ToC div matches the backgroud color. Thats why the ToC is not visible with a dark theme. (screenshot)
But it works on a light theme.
<img width="500" alt="toc" src="https://user-images.githubusercontent.com/33595971/81802865-2376dc00-9517-11ea-9f4d-571a83c4c110.png">

**Comment by JohnMcLear** [comment]
@seballot we will need to do this without any changes to Etherpad core :)

**Comment by seballot** [comment]
ah ah, sorry I do not agree, it's just a missing line in colibris skin, which will benefit to others plugins also ! Fixed here https://github.com/ether/etherpad-lite/pull/3995
